name: Angular CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # - name: Install npm@20
    #   run: npm install -g npm@20

    - name: Install Angular CLI
      run: npm install -g @angular/cli@15.1.4

    - name: Install npm packages
      run: cd sogapeint-CRM/sogapaint-crm && npm install --force

    - name: Run tests
      run: cd sogapeint-CRM/sogapaint-crm && ng test --watch=false --browsers=ChromeHeadless

    # - name: Build
    #   run: cd sogapeint-CRM/sogapaint-crm && ng build --prod
    - name: Compress Project
      run: tar -czf sogapaint-crm.tar.gz -C sogapeint-CRM/sogapaint-crm .

    # Étape de déploiement
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        command_timeout: 30m
        script: |
          echo "Début du déploiement"

          # Transférer le fichier compressé
          echo "debut du transfert"
          scp sogapaint-crm.tar.gz dis@46.105.52.105:/home/dis/dev/
          echo "Transfert OK"

          # Connexion SSH et décompression du fichier
          ssh dis@46.105.52.105 "tar -xzf /home/dis/dev/sogapaint-crm.tar.gz -C /home/dis/dev/app"

          # Nettoyage (optionnel)
          ssh dis@46.105.52.105 "rm /home/dis/dev/sogapaint-crm.tar.gz"

          echo "Déploiement effectué avec succès sur le serveur de test."
