name: Angular CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # - name: Install npm@20
    #   run: npm install -g npm@20

    - name: Install Angular CLI
      run: npm install -g @angular/cli@15.1.4

    - name: Install npm packages
      run: cd sogapeint-CRM/sogapaint-crm && npm install --force

    - name: Run tests
      run: cd sogapeint-CRM/sogapaint-crm && ng test --watch=false --browsers=ChromeHeadless

    - name: Déclencher le webhook pour la branche de test
      if: github.ref == 'refs/heads/dev' && success() 
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL_TEST_SERVER }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      run: |
        PAYLOAD=$(echo -n '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}')
        SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$WEBHOOK_SECRET" | sed 's/^.* //')
        curl -X POST -H "Content-Type: application/json" -H "X-Hub-Signature-256: sha256=$SIGNATURE" -d "$PAYLOAD" "$WEBHOOK_URL"

    - name: Déclencher le webhook pour la branche principale
      if: github.ref == 'refs/heads/main' && success()
      run: |
        echo "aucune commande de déploiement en production n'a encore été défini"