name: Angular CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd sogapeint-CRM/sogapaint-crm && npm install
    - run: cd sogapeint-CRM/sogapaint-crm && npx ng test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - run: cd sogapeint-CRM/sogapaint-crm && npx ng build --prod
