name: Angular CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.9.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd sogapeint-CRM/sogapaint-crm && npm install --force
    - run: cd sogapeint-CRM/sogapaint-crm && ng test --watch=false --browsers=ChromeHeadless
    # - run: cd sogapeint-CRM/sogapaint-crm && ng build --prod
